[2023-07-02T10:02:10.184+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.extract_user scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-02T10:02:10.194+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.extract_user scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-02T10:02:10.194+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-02T10:02:10.195+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-07-02T10:02:10.195+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-02T10:02:10.209+0000] {taskinstance.py:1383} INFO - Executing <Task(SimpleHttpOperator): extract_user> on 2023-07-01 00:00:00+00:00
[2023-07-02T10:02:10.216+0000] {standard_task_runner.py:55} INFO - Started process 42990 to run task
[2023-07-02T10:02:10.234+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'extract_user', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmps507646a']
[2023-07-02T10:02:10.243+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask extract_user
[2023-07-02T10:02:10.380+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.extract_user scheduled__2023-07-01T00:00:00+00:00 [running]> on host 1c40fa061aa3
[2023-07-02T10:02:10.537+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=extract_user
AIRFLOW_CTX_EXECUTION_DATE=2023-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-01T00:00:00+00:00
[2023-07-02T10:02:10.539+0000] {http.py:121} INFO - Calling HTTP method
[2023-07-02T10:02:10.571+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 123, in execute
    response = http.run(self.endpoint, self.data, self.headers, self.extra_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 128, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 82, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `user_api` isn't defined
[2023-07-02T10:02:10.577+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=extract_user, execution_date=20230701T000000, start_date=20230702T100210, end_date=20230702T100210
[2023-07-02T10:02:10.599+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task extract_user (The conn_id `user_api` isn't defined; 42990)
[2023-07-02T10:02:10.669+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-07-02T10:02:10.735+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
