[2023-06-30T15:02:55.652+0000] {processor.py:154} INFO - Started process (PID=22117) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:02:55.654+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:02:55.655+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:02:55.655+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:02:55.774+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:02:55.772+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:02:55.775+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:02:55.798+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.151 seconds
[2023-06-30T15:03:26.398+0000] {processor.py:154} INFO - Started process (PID=22182) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:03:26.400+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:03:26.401+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:03:26.401+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:03:26.451+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:03:26.449+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:03:26.452+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:03:26.470+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.077 seconds
[2023-06-30T15:04:23.883+0000] {processor.py:154} INFO - Started process (PID=22237) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:04:23.885+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:04:23.886+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:04:23.886+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:04:23.950+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:04:23.948+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:04:23.951+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:04:23.971+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.093 seconds
[2023-06-30T15:05:22.243+0000] {processor.py:154} INFO - Started process (PID=22301) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:05:22.248+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:05:22.253+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:05:22.253+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:05:22.416+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:05:22.414+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:05:22.417+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:05:22.439+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.208 seconds
[2023-06-30T15:05:52.520+0000] {processor.py:154} INFO - Started process (PID=22366) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:05:52.522+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:05:52.523+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:05:52.523+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:05:52.579+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:05:52.577+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:05:52.580+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:05:52.602+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.086 seconds
[2023-06-30T15:06:51.506+0000] {processor.py:154} INFO - Started process (PID=22430) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:06:51.508+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:06:51.509+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:06:51.509+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:06:51.566+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:06:51.565+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:06:51.567+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:06:51.586+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.086 seconds
[2023-06-30T15:07:22.129+0000] {processor.py:154} INFO - Started process (PID=22494) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:07:22.130+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:07:22.132+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:07:22.131+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:07:22.176+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:07:22.174+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:07:22.177+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:07:22.195+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.070 seconds
[2023-06-30T15:08:19.296+0000] {processor.py:154} INFO - Started process (PID=22550) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:08:19.298+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:08:19.299+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:08:19.299+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:08:19.349+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:08:19.347+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:08:19.350+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:08:19.366+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2023-06-30T15:09:17.754+0000] {processor.py:154} INFO - Started process (PID=22614) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:09:17.756+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:09:17.758+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:09:17.757+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:09:17.841+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:09:17.838+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:09:17.843+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:09:17.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.119 seconds
[2023-06-30T15:09:48.438+0000] {processor.py:154} INFO - Started process (PID=22677) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:09:48.441+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:09:48.442+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:09:48.442+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:09:48.480+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:09:48.478+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:09:48.481+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:09:48.496+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.061 seconds
[2023-06-30T15:10:47.185+0000] {processor.py:154} INFO - Started process (PID=22740) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:10:47.191+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:10:47.192+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:10:47.192+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:10:47.251+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:10:47.249+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:10:47.252+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:10:47.286+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.106 seconds
[2023-06-30T15:11:45.876+0000] {processor.py:154} INFO - Started process (PID=22795) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:11:45.878+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:11:45.879+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:11:45.879+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:11:45.957+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:11:45.955+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:11:45.957+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:11:45.982+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.111 seconds
[2023-06-30T15:12:16.398+0000] {processor.py:154} INFO - Started process (PID=22858) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:12:16.400+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:12:16.401+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:12:16.401+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:12:16.440+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:12:16.439+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:12:16.442+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:12:16.460+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.066 seconds
[2023-06-30T15:13:13.471+0000] {processor.py:154} INFO - Started process (PID=22922) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:13:13.473+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:13:13.474+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:13:13.474+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:13:13.536+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:13:13.534+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:13:13.537+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:13:13.555+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.090 seconds
[2023-06-30T15:14:12.373+0000] {processor.py:154} INFO - Started process (PID=22983) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:14:12.383+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:14:12.392+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:14:12.392+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:14:12.515+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:14:12.513+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:14:12.516+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:14:12.568+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.210 seconds
[2023-06-30T15:14:42.907+0000] {processor.py:154} INFO - Started process (PID=23041) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:14:42.909+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:14:42.911+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:14:42.910+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:14:42.952+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:14:42.951+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:14:42.953+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:14:42.970+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.066 seconds
[2023-06-30T15:15:41.412+0000] {processor.py:154} INFO - Started process (PID=23104) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:15:41.416+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:15:41.419+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:15:41.419+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:15:41.495+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:15:41.491+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:15:41.501+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:15:41.561+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.154 seconds
[2023-06-30T15:16:12.386+0000] {processor.py:154} INFO - Started process (PID=23168) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:16:12.388+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:16:12.389+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:16:12.389+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:16:12.428+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:16:12.426+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:16:12.429+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:16:12.445+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.063 seconds
[2023-06-30T15:17:09.045+0000] {processor.py:154} INFO - Started process (PID=23231) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:17:09.047+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:17:09.049+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:17:09.049+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:17:09.114+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:17:09.112+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:17:09.115+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:17:09.151+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.112 seconds
[2023-06-30T15:18:07.804+0000] {processor.py:154} INFO - Started process (PID=23286) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:18:07.805+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:18:07.806+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:18:07.806+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:18:07.861+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:18:07.859+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:18:07.861+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:18:07.878+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.078 seconds
[2023-06-30T15:18:38.020+0000] {processor.py:154} INFO - Started process (PID=23351) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:18:38.021+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:18:38.023+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:18:38.022+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:18:38.068+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:18:38.067+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:18:38.070+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:18:38.086+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.069 seconds
[2023-06-30T15:19:36.298+0000] {processor.py:154} INFO - Started process (PID=23414) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:19:36.301+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:19:36.302+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:19:36.302+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:19:36.377+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:19:36.375+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:19:36.381+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:19:36.402+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.110 seconds
[2023-06-30T15:20:34.602+0000] {processor.py:154} INFO - Started process (PID=23477) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:20:34.604+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:20:34.606+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:20:34.606+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:20:34.720+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:20:34.717+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:20:34.721+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:20:34.757+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.165 seconds
[2023-06-30T15:21:05.751+0000] {processor.py:154} INFO - Started process (PID=23531) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:21:05.753+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:21:05.754+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:21:05.754+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:21:05.800+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:21:05.798+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:21:05.802+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:21:05.821+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2023-06-30T15:22:03.898+0000] {processor.py:154} INFO - Started process (PID=23595) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:22:03.899+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:22:03.900+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:22:03.900+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:22:03.964+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:22:03.962+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:22:03.968+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:22:03.991+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.101 seconds
[2023-06-30T15:37:57.139+0000] {processor.py:154} INFO - Started process (PID=23659) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:37:57.148+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:37:57.153+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:37:57.153+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:37:57.333+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:37:57.320+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:37:57.338+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:37:57.407+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.282 seconds
[2023-06-30T15:38:27.538+0000] {processor.py:154} INFO - Started process (PID=23723) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:38:27.540+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:38:27.541+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:38:27.541+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:38:27.617+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:38:27.614+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:38:27.619+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:38:27.652+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.118 seconds
[2023-06-30T15:39:25.805+0000] {processor.py:154} INFO - Started process (PID=23779) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:39:25.807+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:39:25.809+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:39:25.808+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:39:25.855+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:39:25.853+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:39:25.856+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:39:25.876+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.077 seconds
[2023-06-30T15:39:56.227+0000] {processor.py:154} INFO - Started process (PID=23842) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:39:56.230+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:39:56.231+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:39:56.231+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:39:56.292+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:39:56.289+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:39:56.292+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:39:56.313+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.097 seconds
[2023-06-30T15:55:53.891+0000] {processor.py:154} INFO - Started process (PID=23906) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T15:55:53.892+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T15:55:53.894+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:55:53.894+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T15:55:53.947+0000] {logging_mixin.py:120} INFO - [2023-06-30T15:55:53.945+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T15:55:53.948+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T15:55:53.965+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.078 seconds
[2023-06-30T16:03:02.939+0000] {processor.py:154} INFO - Started process (PID=23970) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T16:03:02.951+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T16:03:02.954+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:03:02.954+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T16:03:03.203+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:03:03.194+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T16:03:03.208+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T16:03:03.279+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.357 seconds
[2023-06-30T16:03:33.887+0000] {processor.py:154} INFO - Started process (PID=24025) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T16:03:33.889+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T16:03:33.890+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:03:33.890+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T16:03:33.932+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:03:33.930+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T16:03:33.933+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T16:03:33.951+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.070 seconds
[2023-06-30T16:20:38.417+0000] {processor.py:154} INFO - Started process (PID=24089) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T16:20:38.424+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T16:20:38.426+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:20:38.426+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T16:20:38.605+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:20:38.599+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T16:20:38.608+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T16:20:38.661+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.256 seconds
[2023-06-30T16:21:08.920+0000] {processor.py:154} INFO - Started process (PID=24153) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T16:21:08.922+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T16:21:08.924+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:21:08.924+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T16:21:09.006+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:21:09.003+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T16:21:09.007+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T16:21:09.035+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.121 seconds
[2023-06-30T16:36:48.638+0000] {processor.py:154} INFO - Started process (PID=24217) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T16:36:48.640+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T16:36:48.643+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:36:48.642+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T16:36:48.701+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:36:48.699+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T16:36:48.702+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T16:36:48.778+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.145 seconds
[2023-06-30T16:52:57.582+0000] {processor.py:154} INFO - Started process (PID=24272) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T16:52:57.585+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T16:52:57.589+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:52:57.588+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T16:52:57.767+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:52:57.760+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T16:52:57.776+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T16:52:57.819+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.260 seconds
[2023-06-30T16:53:28.245+0000] {processor.py:154} INFO - Started process (PID=24336) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T16:53:28.247+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T16:53:28.248+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:53:28.248+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T16:53:28.311+0000] {logging_mixin.py:120} INFO - [2023-06-30T16:53:28.309+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T16:53:28.312+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T16:53:28.334+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.098 seconds
[2023-06-30T17:10:48.635+0000] {processor.py:154} INFO - Started process (PID=24400) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T17:10:48.642+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T17:10:48.644+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:10:48.644+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T17:10:48.779+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:10:48.771+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T17:10:48.782+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T17:10:48.818+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.200 seconds
[2023-06-30T17:11:19.399+0000] {processor.py:154} INFO - Started process (PID=24456) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T17:11:19.401+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T17:11:19.404+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:11:19.404+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T17:11:19.459+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:11:19.456+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T17:11:19.460+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T17:11:19.479+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.085 seconds
[2023-06-30T17:11:50.400+0000] {processor.py:154} INFO - Started process (PID=24520) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T17:11:50.403+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T17:11:50.405+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:11:50.405+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T17:11:50.462+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:11:50.460+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T17:11:50.463+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T17:11:50.479+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.082 seconds
[2023-06-30T17:17:16.778+0000] {processor.py:154} INFO - Started process (PID=24584) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T17:17:16.783+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T17:17:16.786+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:17:16.786+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T17:17:16.912+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:17:16.909+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T17:17:16.919+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T17:17:16.957+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.196 seconds
[2023-06-30T17:22:44.369+0000] {processor.py:154} INFO - Started process (PID=24647) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T17:22:44.372+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T17:22:44.373+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:22:44.373+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T17:22:44.452+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:22:44.450+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T17:22:44.453+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T17:22:44.479+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.114 seconds
[2023-06-30T17:23:14.951+0000] {processor.py:154} INFO - Started process (PID=24708) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T17:23:14.954+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T17:23:14.956+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:23:14.956+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T17:23:15.012+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:23:15.010+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T17:23:15.013+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T17:23:15.034+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.087 seconds
[2023-06-30T17:28:41.967+0000] {processor.py:154} INFO - Started process (PID=24766) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T17:28:41.969+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T17:28:41.972+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:28:41.972+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T17:28:42.014+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:28:42.013+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T17:28:42.015+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T17:28:42.040+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.077 seconds
[2023-06-30T17:45:16.707+0000] {processor.py:154} INFO - Started process (PID=24830) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T17:45:16.710+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T17:45:16.711+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:45:16.711+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T17:45:16.772+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:45:16.769+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T17:45:16.773+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T17:45:16.803+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.103 seconds
[2023-06-30T17:45:47.799+0000] {processor.py:154} INFO - Started process (PID=24894) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T17:45:47.801+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T17:45:47.803+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:45:47.803+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T17:45:47.868+0000] {logging_mixin.py:120} INFO - [2023-06-30T17:45:47.865+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T17:45:47.869+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T17:45:47.894+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.105 seconds
[2023-06-30T18:02:24.148+0000] {processor.py:154} INFO - Started process (PID=24949) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T18:02:24.151+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T18:02:24.153+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:02:24.153+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T18:02:24.223+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:02:24.220+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T18:02:24.226+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T18:02:24.248+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.114 seconds
[2023-06-30T18:02:55.171+0000] {processor.py:154} INFO - Started process (PID=25013) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T18:02:55.175+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T18:02:55.177+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:02:55.177+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T18:02:55.244+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:02:55.242+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T18:02:55.246+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T18:02:55.269+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.107 seconds
[2023-06-30T18:20:36.374+0000] {processor.py:154} INFO - Started process (PID=25077) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T18:20:36.397+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T18:20:36.403+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:20:36.403+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T18:20:36.548+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:20:36.537+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T18:20:36.557+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T18:20:36.617+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.266 seconds
[2023-06-30T18:37:49.799+0000] {processor.py:154} INFO - Started process (PID=25141) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T18:37:49.802+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T18:37:49.803+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:37:49.803+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T18:37:49.919+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:37:49.915+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T18:37:49.922+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T18:37:49.964+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.170 seconds
[2023-06-30T18:38:20.354+0000] {processor.py:154} INFO - Started process (PID=25205) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T18:38:20.358+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T18:38:20.361+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:38:20.360+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T18:38:20.490+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:38:20.483+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T18:38:20.491+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T18:38:20.516+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.168 seconds
[2023-06-30T18:55:10.710+0000] {processor.py:154} INFO - Started process (PID=25261) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T18:55:10.716+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T18:55:10.718+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:55:10.718+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T18:55:10.867+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:55:10.862+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T18:55:10.870+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T18:55:10.971+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.267 seconds
[2023-06-30T18:55:41.381+0000] {processor.py:154} INFO - Started process (PID=25326) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T18:55:41.384+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T18:55:41.386+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:55:41.386+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T18:55:41.479+0000] {logging_mixin.py:120} INFO - [2023-06-30T18:55:41.476+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T18:55:41.480+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T18:55:41.520+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.144 seconds
[2023-06-30T19:12:04.685+0000] {processor.py:154} INFO - Started process (PID=25390) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T19:12:04.687+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T19:12:04.687+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:12:04.687+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T19:12:04.742+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:12:04.739+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T19:12:04.743+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T19:12:04.767+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.091 seconds
[2023-06-30T19:12:35.502+0000] {processor.py:154} INFO - Started process (PID=25454) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T19:12:35.503+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T19:12:35.504+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:12:35.504+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T19:12:35.563+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:12:35.560+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T19:12:35.564+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T19:12:35.593+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.097 seconds
[2023-06-30T19:23:23.576+0000] {processor.py:154} INFO - Started process (PID=25508) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T19:23:23.579+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T19:23:23.581+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:23:23.581+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T19:23:23.692+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:23:23.688+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T19:23:23.694+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T19:23:23.732+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.166 seconds
[2023-06-30T19:23:54.177+0000] {processor.py:154} INFO - Started process (PID=25572) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T19:23:54.180+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T19:23:54.181+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:23:54.181+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T19:23:54.246+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:23:54.240+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T19:23:54.249+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T19:23:54.278+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.104 seconds
[2023-06-30T19:24:24.993+0000] {processor.py:154} INFO - Started process (PID=25636) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T19:24:24.996+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T19:24:24.997+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:24:24.997+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T19:24:25.060+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:24:25.057+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T19:24:25.061+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T19:24:25.088+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.100 seconds
[2023-06-30T19:40:30.508+0000] {processor.py:154} INFO - Started process (PID=25691) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T19:40:30.519+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T19:40:30.524+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:40:30.524+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T19:40:30.718+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:40:30.714+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T19:40:30.723+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T19:40:30.771+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.289 seconds
[2023-06-30T19:57:10.841+0000] {processor.py:154} INFO - Started process (PID=25756) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T19:57:10.850+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T19:57:10.853+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:57:10.853+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T19:57:11.115+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:57:11.109+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T19:57:11.116+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T19:57:11.162+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.339 seconds
[2023-06-30T19:57:41.684+0000] {processor.py:154} INFO - Started process (PID=25821) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T19:57:41.687+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T19:57:41.689+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:57:41.689+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T19:57:41.755+0000] {logging_mixin.py:120} INFO - [2023-06-30T19:57:41.753+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T19:57:41.757+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T19:57:41.785+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.113 seconds
[2023-06-30T20:13:28.557+0000] {processor.py:154} INFO - Started process (PID=25885) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T20:13:28.561+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T20:13:28.562+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:13:28.562+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T20:13:28.682+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:13:28.673+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T20:13:28.685+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T20:13:28.739+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.191 seconds
[2023-06-30T20:13:58.990+0000] {processor.py:154} INFO - Started process (PID=25947) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T20:13:58.996+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T20:13:58.999+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:13:58.999+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T20:13:59.064+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:13:59.061+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T20:13:59.072+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T20:13:59.103+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.119 seconds
[2023-06-30T20:14:29.608+0000] {processor.py:154} INFO - Started process (PID=26004) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T20:14:29.610+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T20:14:29.611+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:14:29.611+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T20:14:29.666+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:14:29.664+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T20:14:29.668+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T20:14:29.690+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.085 seconds
[2023-06-30T20:32:40.749+0000] {processor.py:154} INFO - Started process (PID=26067) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T20:32:40.751+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T20:32:40.753+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:32:40.752+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T20:32:40.811+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:32:40.809+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T20:32:40.812+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T20:32:40.828+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.082 seconds
[2023-06-30T20:49:57.783+0000] {processor.py:154} INFO - Started process (PID=26131) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T20:49:57.786+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T20:49:57.788+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:49:57.788+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T20:49:57.887+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:49:57.884+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T20:49:57.888+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T20:49:57.919+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.143 seconds
[2023-06-30T20:50:28.692+0000] {processor.py:154} INFO - Started process (PID=26195) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T20:50:28.695+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T20:50:28.697+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:50:28.697+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T20:50:28.779+0000] {logging_mixin.py:120} INFO - [2023-06-30T20:50:28.776+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T20:50:28.781+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T20:50:28.812+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.131 seconds
[2023-06-30T21:06:13.586+0000] {processor.py:154} INFO - Started process (PID=26250) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T21:06:13.593+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T21:06:13.594+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:06:13.594+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T21:06:13.715+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:06:13.710+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T21:06:13.719+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T21:06:13.780+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.201 seconds
[2023-06-30T21:06:44.446+0000] {processor.py:154} INFO - Started process (PID=26313) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T21:06:44.449+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T21:06:44.451+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:06:44.451+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T21:06:44.511+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:06:44.509+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T21:06:44.512+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T21:06:44.540+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.100 seconds
[2023-06-30T21:22:41.062+0000] {processor.py:154} INFO - Started process (PID=26377) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T21:22:41.064+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T21:22:41.066+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:22:41.066+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T21:22:41.126+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:22:41.124+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T21:22:41.128+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T21:22:41.151+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.095 seconds
[2023-06-30T21:23:11.561+0000] {processor.py:154} INFO - Started process (PID=26441) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T21:23:11.563+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T21:23:11.564+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:23:11.564+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T21:23:11.624+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:23:11.621+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T21:23:11.626+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T21:23:11.654+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.097 seconds
[2023-06-30T21:40:17.139+0000] {processor.py:154} INFO - Started process (PID=26496) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T21:40:17.141+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T21:40:17.142+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:40:17.142+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T21:40:17.181+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:40:17.179+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T21:40:17.182+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T21:40:17.198+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2023-06-30T21:40:47.631+0000] {processor.py:154} INFO - Started process (PID=26559) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T21:40:47.634+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T21:40:47.636+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:40:47.636+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T21:40:47.704+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:40:47.701+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T21:40:47.705+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T21:40:47.729+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.105 seconds
[2023-06-30T21:58:49.071+0000] {processor.py:154} INFO - Started process (PID=26622) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T21:58:49.072+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T21:58:49.073+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:58:49.073+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T21:58:49.153+0000] {logging_mixin.py:120} INFO - [2023-06-30T21:58:49.151+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T21:58:49.154+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T21:58:49.197+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.130 seconds
[2023-06-30T22:14:37.890+0000] {processor.py:154} INFO - Started process (PID=26686) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T22:14:37.894+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T22:14:37.898+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:14:37.897+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T22:14:38.035+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:14:38.033+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T22:14:38.039+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T22:14:38.084+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.211 seconds
[2023-06-30T22:15:08.485+0000] {processor.py:154} INFO - Started process (PID=26741) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T22:15:08.487+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T22:15:08.488+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:15:08.488+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T22:15:08.530+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:15:08.529+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T22:15:08.531+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T22:15:08.551+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.069 seconds
[2023-06-30T22:32:26.833+0000] {processor.py:154} INFO - Started process (PID=26805) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T22:32:26.838+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T22:32:26.841+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:32:26.841+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T22:32:26.995+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:32:26.989+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T22:32:26.996+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T22:32:27.027+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.204 seconds
[2023-06-30T22:32:57.174+0000] {processor.py:154} INFO - Started process (PID=26868) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T22:32:57.176+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T22:32:57.177+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:32:57.177+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T22:32:57.236+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:32:57.230+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T22:32:57.237+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T22:32:57.274+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.106 seconds
[2023-06-30T22:49:42.616+0000] {processor.py:154} INFO - Started process (PID=26932) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T22:49:42.618+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T22:49:42.619+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:49:42.619+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T22:49:42.692+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:49:42.685+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T22:49:42.696+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T22:49:42.743+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.134 seconds
[2023-06-30T22:50:13.373+0000] {processor.py:154} INFO - Started process (PID=26986) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T22:50:13.375+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T22:50:13.377+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:50:13.377+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T22:50:13.426+0000] {logging_mixin.py:120} INFO - [2023-06-30T22:50:13.425+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T22:50:13.427+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T22:50:13.449+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.082 seconds
[2023-06-30T23:00:04.887+0000] {processor.py:154} INFO - Started process (PID=27050) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:00:04.890+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:00:04.892+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:00:04.892+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:00:05.014+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:00:05.009+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:00:05.016+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:00:05.063+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.181 seconds
[2023-06-30T23:00:35.880+0000] {processor.py:154} INFO - Started process (PID=27114) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:00:35.884+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:00:35.887+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:00:35.887+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:00:35.941+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:00:35.940+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:00:35.942+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:00:35.972+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.095 seconds
[2023-06-30T23:01:06.744+0000] {processor.py:154} INFO - Started process (PID=27178) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:01:06.747+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:01:06.752+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:01:06.752+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:01:06.822+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:01:06.818+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:01:06.824+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:01:06.855+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.116 seconds
[2023-06-30T23:01:37.688+0000] {processor.py:154} INFO - Started process (PID=27242) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:01:37.690+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:01:37.690+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:01:37.690+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:01:37.741+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:01:37.740+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:01:37.742+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:01:37.760+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.079 seconds
[2023-06-30T23:02:07.980+0000] {processor.py:154} INFO - Started process (PID=27306) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:02:07.983+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:02:07.984+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:02:07.984+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:02:08.040+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:02:08.036+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:02:08.042+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:02:08.068+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.091 seconds
[2023-06-30T23:02:38.716+0000] {processor.py:154} INFO - Started process (PID=27361) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:02:38.718+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:02:38.720+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:02:38.720+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:02:38.770+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:02:38.769+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:02:38.771+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:02:38.793+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.082 seconds
[2023-06-30T23:03:09.190+0000] {processor.py:154} INFO - Started process (PID=27425) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:03:09.192+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:03:09.194+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:03:09.194+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:03:09.252+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:03:09.250+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:03:09.253+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:03:09.273+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.088 seconds
[2023-06-30T23:03:40.072+0000] {processor.py:154} INFO - Started process (PID=27490) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:03:40.073+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:03:40.074+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:03:40.074+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:03:40.121+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:03:40.119+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:03:40.122+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:03:40.141+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.073 seconds
[2023-06-30T23:04:10.956+0000] {processor.py:154} INFO - Started process (PID=27554) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:04:10.958+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:04:10.959+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:04:10.959+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:04:11.023+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:04:11.021+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:04:11.025+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:04:11.047+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.099 seconds
[2023-06-30T23:04:41.463+0000] {processor.py:154} INFO - Started process (PID=27618) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:04:41.464+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:04:41.465+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:04:41.465+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:04:41.503+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:04:41.501+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:04:41.504+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:04:41.520+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.062 seconds
[2023-06-30T23:05:12.133+0000] {processor.py:154} INFO - Started process (PID=27682) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:05:12.135+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:05:12.136+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:05:12.136+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:05:12.185+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:05:12.183+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:05:12.186+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:05:12.206+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.079 seconds
[2023-06-30T23:05:42.886+0000] {processor.py:154} INFO - Started process (PID=27737) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:05:42.889+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:05:42.891+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:05:42.890+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:05:42.944+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:05:42.942+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:05:42.946+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:05:42.966+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.085 seconds
[2023-06-30T23:06:13.095+0000] {processor.py:154} INFO - Started process (PID=27800) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:06:13.097+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:06:13.099+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:06:13.099+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:06:13.154+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:06:13.152+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:06:13.155+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:06:13.178+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.089 seconds
[2023-06-30T23:06:43.984+0000] {processor.py:154} INFO - Started process (PID=27864) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:06:43.986+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:06:43.988+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:06:43.988+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:06:44.034+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:06:44.032+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:06:44.035+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:06:44.054+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.074 seconds
[2023-06-30T23:07:14.775+0000] {processor.py:154} INFO - Started process (PID=27927) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:07:14.777+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:07:14.778+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:07:14.778+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:07:14.820+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:07:14.819+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:07:14.823+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:07:14.843+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.072 seconds
[2023-06-30T23:07:45.740+0000] {processor.py:154} INFO - Started process (PID=27990) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:07:45.742+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:07:45.743+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:07:45.743+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:07:45.792+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:07:45.789+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:07:45.793+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:07:45.815+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.078 seconds
[2023-06-30T23:08:16.392+0000] {processor.py:154} INFO - Started process (PID=28054) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:08:16.394+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:08:16.395+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:08:16.395+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:08:16.452+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:08:16.450+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:08:16.453+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:08:16.472+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.084 seconds
[2023-06-30T23:08:47.029+0000] {processor.py:154} INFO - Started process (PID=28117) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:08:47.032+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:08:47.033+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:08:47.033+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:08:47.076+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:08:47.074+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:08:47.078+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:08:47.095+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.069 seconds
[2023-06-30T23:09:17.938+0000] {processor.py:154} INFO - Started process (PID=28172) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:09:17.941+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:09:17.944+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:09:17.944+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:09:18.058+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:09:18.056+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:09:18.060+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:09:18.095+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.168 seconds
[2023-06-30T23:09:48.617+0000] {processor.py:154} INFO - Started process (PID=28234) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:09:48.620+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:09:48.622+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:09:48.622+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:09:48.700+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:09:48.697+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:09:48.701+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:09:48.731+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.122 seconds
[2023-06-30T23:10:19.442+0000] {processor.py:154} INFO - Started process (PID=28299) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:10:19.445+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:10:19.447+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:10:19.447+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:10:19.537+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:10:19.534+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:10:19.538+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:10:19.573+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.137 seconds
[2023-06-30T23:10:49.867+0000] {processor.py:154} INFO - Started process (PID=28355) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:10:49.870+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:10:49.871+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:10:49.871+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:10:49.953+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:10:49.951+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:10:49.955+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:10:49.991+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.131 seconds
[2023-06-30T23:11:20.394+0000] {processor.py:154} INFO - Started process (PID=28410) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:11:20.397+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:11:20.399+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:11:20.399+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:11:20.489+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:11:20.487+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:11:20.491+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:11:20.525+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.136 seconds
[2023-06-30T23:11:51.157+0000] {processor.py:154} INFO - Started process (PID=28464) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:11:51.160+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:11:51.164+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:11:51.164+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:11:51.300+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:11:51.295+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:11:51.304+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:11:51.396+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.250 seconds
[2023-06-30T23:12:21.565+0000] {processor.py:154} INFO - Started process (PID=28528) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:12:21.574+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:12:21.582+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:12:21.581+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:12:21.809+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:12:21.798+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:12:21.825+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:12:21.942+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.391 seconds
[2023-06-30T23:12:52.295+0000] {processor.py:154} INFO - Started process (PID=28583) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:12:52.300+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:12:52.302+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:12:52.302+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:12:52.402+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:12:52.399+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:12:52.404+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:12:52.445+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.159 seconds
[2023-06-30T23:13:22.575+0000] {processor.py:154} INFO - Started process (PID=28638) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:13:22.580+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:13:22.585+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:13:22.585+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:13:22.675+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:13:22.672+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:13:22.677+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:13:22.715+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.147 seconds
[2023-06-30T23:13:53.054+0000] {processor.py:154} INFO - Started process (PID=28693) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:13:53.058+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:13:53.059+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:13:53.059+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:13:53.148+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:13:53.145+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:13:53.150+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:13:53.190+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.143 seconds
[2023-06-30T23:14:24.050+0000] {processor.py:154} INFO - Started process (PID=28756) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:14:24.053+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:14:24.055+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:14:24.055+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:14:24.140+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:14:24.137+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:14:24.142+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:14:24.177+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.134 seconds
[2023-06-30T23:14:54.943+0000] {processor.py:154} INFO - Started process (PID=28811) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:14:54.946+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:14:54.948+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:14:54.948+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:14:55.053+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:14:55.049+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:14:55.056+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:14:55.097+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.161 seconds
[2023-06-30T23:31:16.099+0000] {processor.py:154} INFO - Started process (PID=28827) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:31:16.100+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:31:16.102+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:31:16.101+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:31:16.153+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:31:16.151+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:31:16.154+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:31:16.172+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.078 seconds
[2023-06-30T23:31:47.001+0000] {processor.py:154} INFO - Started process (PID=28891) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:31:47.003+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:31:47.004+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:31:47.004+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:31:47.051+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:31:47.049+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:31:47.052+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:31:47.073+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.077 seconds
[2023-06-30T23:47:46.772+0000] {processor.py:154} INFO - Started process (PID=28945) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:47:46.774+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:47:46.777+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:47:46.777+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:47:46.833+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:47:46.831+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:47:46.834+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:47:46.856+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.089 seconds
[2023-06-30T23:58:10.985+0000] {processor.py:154} INFO - Started process (PID=29009) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:58:10.990+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:58:10.992+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:58:10.992+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:58:11.145+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:58:11.140+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:58:11.148+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:58:11.190+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.212 seconds
[2023-06-30T23:58:41.291+0000] {processor.py:154} INFO - Started process (PID=29073) to work on /opt/airflow/dags/user_processing.py
[2023-06-30T23:58:41.293+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/user_processing.py for tasks to queue
[2023-06-30T23:58:41.295+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:58:41.294+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/user_processing.py
[2023-06-30T23:58:41.385+0000] {logging_mixin.py:120} INFO - [2023-06-30T23:58:41.382+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/user_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_processing.py", line 8, in <module>
    schedule_interval='@daily', default_args=DEFAULT_ARGS, catchup=False) as dag:
NameError: name 'DEFAULT_ARGS' is not defined
[2023-06-30T23:58:41.387+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/user_processing.py
[2023-06-30T23:58:41.425+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/user_processing.py took 0.140 seconds
